import React from 'react';
import './globals.css';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import Navbar from './_components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
